---
- name: make sure that no hosts in the ipaprimary group are in the ipareplica group too
  ansible.builtin.assert:
    that:
      - not(inventory_hostname in groups['ipaprimary'] and inventory_hostname  in groups['ipareplicas'])

- name: check if we have previous restore state
  ansible.builtin.stat:
    path: "{{ ipa_container_state_path }}/var/lib/ipa/sysrestore/sysrestore.state"
  register: existing_ipa_data
  
- name: copy ipa_install monitor script
  ansible.builtin.copy:
    src: monitor_ipa_install.sh
    dest: /root/monitor_ipa_install.sh
    owner: root
    group: root
    mode: '0755'
  become: true
  
- name: bootstrap primary
  ansible.builtin.include_tasks: bootstrap_initial_container.yml
  tags:
    - ipa-primary-bootstrap
  when: 
    - not existing_ipa_data.stat.exists | bool
    - inventory_hostname in groups['ipaprimary']

- name: bootstrap replica(s)
  ansible.builtin.include_tasks: bootstrap_initial_container.yml
  when: 
    - not existing_ipa_data.stat.exists | bool
    - inventory_hostname in groups['ipareplicas']
  tags:
    - ipa-replica-bootstrap

- name: remove freeipa {{ipa_container_type}} bootstrap container
  containers.podman.podman_container:
    name: "freeipa-{{ipa_container_type}}-bootstrap"
    state: absent
  become: true


- name: ensure freeipa container in started
  containers.podman.podman_container:
    name: freeipa-{{ipa_container_type}}
    detach: true
    recreate: false
    image: "{{ ipa_container_remote }}"
    restart_policy: "no"
    rm: false
    user: root
    network: host
    state: started 
    volume:
      - /var/lib/state:/data:Z
      - /etc/localtime:/etc/localtime:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: "{{ ipa_container_create_commands[ipa_container_type] }}"
  become: true
  register: ipa_container

- debug:
    var: ipa_container

- name: Create systemd unit file
  ansible.builtin.template:
    dest: /usr/lib/systemd/system/ipa-podman.service
    src: ipa-podman.service.j2
  become: true
  notify: Restart ipa-podman container


- ansible.builtin.meta: flush_handlers
  
- name: ensure ipa-podman service is in desired state
  ansible.builtin.systemd:
    name: ipa-podman
    state: "{{ ipa_container_service_state }}"
  become: true
