---
- name: Ensure ipaprimary node is in inventory
  hosts: all
  tasks:
    - assert:
        that: groups['ipaprimary'] | length
        fail_msg: "no hosts found in group 'ipaprimary' - has ipaprimary node been deployed?"

- name: Validate podman configuration
  hosts: podman
  tags: podman
  tasks:
    - import_role:
        name: podman
        tasks_from: validate.yml
      tags: validate